<?php

/**
 * @file
 * Contains site_location_time.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function site_location_time_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the site_location_time module.
    case 'help.page.site_location_time':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Simple modulke to configure the site location and its Timezone.') . '</p>';
      return $output;

    default:
  }
}
